version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ybkk1027
      MYSQL_DATABASE: website_qdqtrj
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '3307:3307'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  memcached:
    image: memcached:1.6-alpine
    restart: always
    ports:
      - '11212:11212'
    command: memcached -m 64
volumes:
  mysql: ~
